
dev : 
	python -m venv .venv
	source .venv/bin/activate
pipup :
	python3 -m pip install --upgrade pip
install :
	pip install -r requirements.txt
freeze:
	pip freeze > requirements.txt
run : 
	python app.py
	